import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar"
import FullScreenNav from "@/components/Navigation/FullScreenNav";
import { NavbarProvider } from "@/context/NavContext";
import Stairs from "@/components/common/Stairs";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // You can choose weights as needed
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${montserrat.variable} ${roboto.variable} antialiased`}
      >
        <NavbarProvider>
          <Stairs>
            <Navbar />
            <FullScreenNav />
            {children}
          </Stairs>
        </NavbarProvider>
      </body>
    </html>
  );
}
